NewsApp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from users import views as user_views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from users import views as user_views
urlpatterns = [
    path('', views.home, name='home' ),
    path('description/<int:id>', views.description, name='description'),
    path('category/<int:id>', views.category, name='category'),
    path('like/<int:pk>', views.like, name='like_article'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name= models.CharField(max_length=200)
    category_image= models.ImageField(upload_to='imgs')
    class Meta:
        verbose_name_plural='Categories'
    def __str__(self):
        return self.name

class News(models.Model):
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    image= models.ImageField(upload_to='imgs/')
    description=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)
    likes=models.ManyToManyField(User,related_name='article')
    class Meta:
        verbose_name_plural='News'
    def __str__(self):
        return self.title
    def total_likes(self):
        return self.likes.count()

class Comment(models.Model):
    news=models.ForeignKey(News, related_name="comments",on_delete=models.CASCADE)
    user=models.ForeignKey(User, related_name="comments",on_delete=models.CASCADE)  
    body=models.TextField()
    reply = models.ForeignKey('Comment', null=True, related_name="replies", on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '{}-{}'.format(self.news.title, str(self.user.username))

    

mainapp/forms.py
from django import forms
from .models import Comment
from django.contrib.auth.models import User

class CommentForm(forms.ModelForm):
    body = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your comment...', 'rows':3, 'cols': 100}))
    class Meta:
        model = Comment
        fields = ('body',)

mainapp/views.py
import datetime as D  # datetime library to get time for setting cookie
import sys
from django.shortcuts import render,get_object_or_404
from django.utils import timezone
from django.urls import path, reverse, reverse_lazy 
from django.template import RequestContext, loader
from django.http import HttpResponseRedirect
from django.contrib.auth.hashers import make_password
from django.db import IntegrityError
from django.conf.urls.static import static
from users.models import UserProfile
from .models import Comment
from .forms import *
from django.contrib.auth.decorators import login_required
from .models import News,Category


@login_required
def home(request):
    latest=News.objects.first()
    corresponding=News.objects.all()[1:4]
    #We have fetched the latest article in the news object
    #Then we fetcjed the next 3 latest articles stored in corresponding
    categories=Category.objects.all()
    #This is used for the dropdown in nac
    x=request.user.userprofile.favourite.all()
    #Used to filter the users articles
    return render(request,'articles.html',{
        'latest':latest,
        'corresponding':corresponding,
        'cats':categories,
        'favcats':x
 
    })


def description(request, id):
    news=News.objects.get(pk=id)
    category=Category.objects.get(id=news.category.id)
    similar=News.objects.filter(category=category).exclude(id=id)
    #Used to filter articles to those similar to the current cateogry
    comments = Comment.objects.filter(news=news, reply=None).order_by('-id')
    #Used to order comments
    categories=Category.objects.all()
    is_liked = False
    if news.likes.filter(id=request.user.id).exists():
        is_liked = True
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            body = request.POST.get('body')
            reply_id = request.POST.get('comment_id')
            comment_qs= None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(news=news, user=request.user, body=body, reply=comment_qs)
            comment.save()
            #Saves a comment in the db
    else:
        comment_form = CommentForm()

    return render(request,'description.html',
    {
          'news':news,
          'similar':similar,
          'cats':categories,
          'comments': comments,
          'comment_form': comment_form,
          'is_liked': is_liked,
          'total_likes': news.total_likes()
    })

def category(request,id):
    
    category=Category.objects.get(id=id)
    news=News.objects.filter(category=category)
    categories=Category.objects.all()
    return render(request,'category.html',
    {
        'catnews':news,
        'category':category,
        'cats':categories,
    })
    
def like(request, pk):
    news = News.objects.get(id=pk)
    is_liked = False
    if news.likes.filter(id=request.user.id).exists():
        news.likes.remove(request.user)
        is_liked = False
    else:
        news.likes.add(request.user)
        is_liked = True
    #Like has been assigned from that user to that news object
    return HttpResponseRedirect(reverse('description', args=[str(pk)]))
    

mainapp/templates/articles.html
{% extends "home.html" %}

{% block content %}
<!--Main-->
  <main class="container mt-3 mb-5">
  <p class='h1'>Latest News</p>
    <div class="row my-3">
    <!--Left-->
      <div class="col-md-7">
        <div class="card mb-3">
          <img src='{{latest.image.url}}' class="card-img-top" alt="{{latest.title}}">
          <div class="card-body">
            <h5 class="card-title">{{latest.title}}</h5>
            <hr/>
            <p class="card-text">
              <a href="/description/{{latest.id}}" class="btn btn-sm btn-primary">Read Full</a>
            </p>
          </div>
        </div>
      </div>
      <!--Right-->
      <div class="col-md-5" >
        {% for news in corresponding%}
        <div class="card">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img src='{{news.image.url}}' class="card-img-top" alt="{{news.title}}">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{news.title}}</h5>
                <p class="card-text"><a href="/description/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
              </div>
            </div>
          </div>
        </div>
        <hr/>
        {% endfor %}
        
      </div>
    </div>
    {%for category in cats%}
    <h3 class="border-bottom pb-1">{{category.name}}  </h3>
	<div class="row my-4">
		<!-- News box -->
    {%for news in category.news_set.all%}
		<div class="col-md-3">
			<div class="card mb-3 shadow">
			  <img src="{{news.image.url}}" class="card-img-top" alt="News 1">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/description/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
		</div>
    {%endfor%}
  </div>
  {%endfor%}
  </main>
{% endblock %}

mainapp/templates/articles1.html
{% extends "home.html" %}

{% block content %}
<!--Main-->
  <main class="container mt-3 mb-5">
  <p class='h1'>Latest News</p>
    <div class="row my-3">
    <!--Left-->
      <div class="col-md-7">
        <div class="card mb-3">
          <img src='{{latest.image.url}}' class="card-img-top" alt="{{latest.title}}">
          <div class="card-body">
            <h5 class="card-title">{{latest.title}}</h5>
            <hr/>
            <p class="card-text">
              <a href="/description/{{latest.id}}" class="btn btn-sm btn-primary">Read Full</a>
            </p>
          </div>
        </div>
      </div>
      <!--Right-->
      <div class="col-md-5" >
        {% for news in corresponding%}
        <div class="card">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img src='{{news.image.url}}' class="card-img-top" alt="{{news.title}}">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{news.title}}</h5>
                <p class="card-text"><a href="/description/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
              </div>
            </div>
          </div>
        </div>
        <hr/>
        {% endfor %}
        
      </div>
    </div>

  </main>
{% endblock %}

mainapp/templates/category.html
{%extends 'home.html'%}
{% block content %}

<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">{{category.name}}</h3>
	<!-- News Box -->
	{%for news in catnews%}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
	      <img src="{{news.image.url}}" class="card-img" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.description}}</p>
	        <p class="card-text"><a href="/description/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
	      </div>
	    </div>
	  </div>
	</div>
	{%endfor%}
	
</main>


{% endblock %}

mainapp/templates/description.html
{%extends 'home.html'%}
{%block content%}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-8">
			<div class="card mb-3">
				<img src='{{news.image.url}}' class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr />
					<p class="card-text">{{news.description}}</p>
				</div>
				<div class="card-footer">
					<a href="/category/{{news.category.id}}">{{news.category.title}}</a>
					<form action="{%url 'like_article' news.pk%}" method="POST">
						{% csrf_token %}
						{% if user.is_authenticated %}
						{% if is_liked %}
						<button type="submit" name="article_id" , class="btn btn-danger">Dislike</button>
						{% else %}
						<button type="submit" name="article_id" , class="btn btn-primary">Like</button> Likes -
						{{total_likes}}
						{% endif %}
						{% else %}
						<small>Login To Like</small>
						{% endif %}
					</form>
				</div>
			</div>
			<!-- Previous Comments -->
			<div class="card my-4">
				<h6 class="card-header">Comments</h6>

				<div class="card-body">
					{%if not news.comments.all%}
					<blockquote class="blockquote text-right">
						<p class="mb-0">This article has no comments yet...</p>
						<footer class="blockquote-footer"> <cite title="Source Title"></cite></footer>
					</blockquote>
					{% else %}
					{{comments.count}} Comment{{comments|pluralize}}
					{%for comment in comments%}
					<blockquote class="blockquote text-right">
						<p class="mb-0">{{comment.body}}</p>
						<footer class="blockquote-footer"><cite title="Source Title">by {{comment.user}}</cite>
							<a href="#" class="reply-btn">Reply</a>
						</footer>
					</blockquote>
					<div class="replied-comments container mt-2" style="display: none;">
						{% for reply in comment.replies.all %}
						<blockquote class="blockquote text-right">
							<p class="mb-0"><small>{{reply.body}}</small></p>
							<footer class="blockquote-footer"><small><cite title="Source Title">by
										{{reply.user}}</cite></small>
							</footer>

						</blockquote>
						{% endfor %}
						<form method="post">
							{% csrf_token %}
							<input type="hidden" name="comment_id" value="{{ comment.id }}">
							{{comment_form.as_p}}
							{% if user.is_authenticated %}
							<input type="submit" value="Submit" class="btn btn-outline-success" />
							{% else %}
							<input type="submit" value="Submit" class="btn btn-outline-success" disabled />
							<small>Login To
								Comment</small>
							{% endif %}
						</form>

					</div>
					{%endfor%}
					{%endif%}
					<hr />

				</div>
			</div>
			<!-- Comments -->

			<div class="card my-4">
				<h6 class="card-header">Add Comment</h6>
				<div class="card-body">
					<form method="post">
						{% csrf_token %}
						{{comment_form.as_p}}
						{% if user.is_authenticated %}
						<input type="submit" value="Submit" class="btn btn-outline-success" />
						{% else %}
						<input type="submit" value="Submit" class="btn btn-outline-success" disabled />
						<small>Login To
							Comment</small>
						{% endif %}
					</form>
				</div>
			</div>
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">From this Category</h3>
			<!-- Category Box -->
			{%for news in similar%}
			<div class="card mb-3 shadow">
				<img src='{{news.image.url}}' class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr />
					<p class="card-text"><a href="/description/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a>
					</p>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</main>

{% endblock %}

mainapp/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>


  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  {% comment %}
  <link rel="stylesheet" href="{%static 'home.css'%}" {% endcomment %} </head>

<body>
  <!--Navbar-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container">
      <a class="navbar-brand" href="{%url 'home'%}">QM News</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'home'%}">Home</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Categories
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for cat in cats%}
              <a class="dropdown-item" href="/category/{{cat.id}}">{{cat.name}}</a>

              {%endfor%}
            </div>

          </li>
          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}}
  {% endblock %}

  <hr />
  <footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <a href="#">Back to top<a>
      </p>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

  {% block main %}
  {% endblock %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      $('.reply-btn').click(function (event) {
        event.preventDefault();
        $(this).parent().parent().next('.replied-comments').fadeToggle();
      });
    });
  </script>
</body>

</html>